### ISSUE TITLE
Installer Version 2.0.0.31 not recognized

### ISSUE THREAD

**Issue by nightlark** [Bioruebe/cicdec#1]
I found an installer for a fairly old game (last update was around 2009) that seems to be made with CIC version 2.0.0.31, though cicdec isn't able to recognize the version number. Manually extracting some of the compressed data files seemed to work.

The direct download link is http://www.synthetic-reality.us/WellOfSouls.exe
The download page is http://synthetic-reality.com/wosDownload.htm

**Comment by Bioruebe** [comment]
Thanks for reporting the problem. Fixed :)
