### ISSUE TITLE
ClickTeam Installer fails to extract; GUI possible?

### ISSUE THREAD

**Issue by sjkorvin** [Bioruebe/cicdec#2]
Hello. The Simtropolis city builder game community has discovered cicdec and we are elated over it. Thank you very much for this utility. Firstly, I would please like to ask if a GUI is in the works for cicdec. A GUI would certainly make cicdec easier to use. Additionally, I have found a ClickTeam installer that cicdec fails to extract. Included below is a screenshot of the failed extraction. Please understand that I will not attach the ClickTeam installer in order to honor and respect distribution choices of creators in the SimCity 4 community. Thank you very much.

<img width="865" alt="WindowsTerminal_2021-02-07_16-14-23" src="https://user-images.githubusercontent.com/50928154/107160025-acfdf200-6961-11eb-9ecc-3b026ff5d5ab.png">

The installer can be downloaded here: https://sc4devotion.com/csxlex/lex_filedesc.php?lotGET=3244

Please note that you will have to create an account in order to download anything from the SC4Devotion Lot Exchange.

**Comment by Bioruebe** [comment]
Hi. Thanks for your nice words. It's great to see that my tool is useful for you :)

1. A separate GUI for cicdec is not planned, however [Universal Extractor](https://github.com/Bioruebe/UniExtract2) serves as a GUI, which combines all my extractors (and many more). Additionally, my command line tools support drag & drop. Simply drop any supported installer onto `cicdec.exe` and the extraction should work without having to fiddle with the command line.

2. Interesting find, that's an installer version I have never seen before. Thanks for reporting it here. Will be supported in the next version of cicdec 🥳

**Comment by sjkorvin** [comment]
You're welcome! I had discovered Universal Extractor 2 before you had responded to my opened issue. Thank you again!

**Comment by DevX-Cipher** [comment]
i have made GUI check out the pull request
